name: update-neuvector-upgrade-responder

on:
  workflow_dispatch:

jobs:
  checker-nuevector-upgrade-responder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write 
    env:
      COMMIT_MESSAGE: "Automated commit by GitHub Actions"
      BRANCH_NAME_PREFIX: "auto-update/neuvector-upgrade-responder-"
      GIT_PATH_NEUVECTOR: "neuvector/"
      FILE_PATH_NEUVECTOR:
    
    steps:
      - name: Checkout external-production repository
        uses: actions/checkout@v4
        with:
          #repository: rancher-eio/external-production
          ref: main
          sparse-checkout: |
            manifests/upgrade-responder/resources/ConfigMap/
          sparse-checkout-cone-mode: true

      - name: Checkout neuvector repository (only upgrade-responder.json)
        uses: actions/checkout@v4
        with:
          repository: anarkis/neuvector
          ref: main
          path: ${{ env.GIT_PATH_NEUVECTOR }}
          sparse-checkout: |
            .github/upgrade-responder.json
          sparse-checkout-cone-mode: true

      - name: ls folders
        run: |
          ls -la .
          ls -la neuvector/

      - name: Compare upgrade-responder versions
        id: checker-diff-files
        run: |
          if diff -q manifests/upgrade-responder/resources/ConfigMap/upgrade-responder.json neuvector/.github/upgrade-responder.json; then
            echo "TRUE: Files are identical"
            echo "TO_BE_UPDATED=false" >> "$GITHUB_OUTPUT"
          else
            echo "FALSE: Files differ"
            echo "TO_BE_UPDATED=true" >> "$GITHUB_OUTPUT"
            TAG=$(jq ".Versions[0].Tags[1]" neuvector/.github/upgrade-responder.json | tr -d "\"")
            echo "TAG_TO_UPDATE=$TAG" >> "$GITHUB_OUTPUT"
          fi

      - name: Set git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update external-production upgrade-responder file
        if: ${{ steps.checker-diff-files.outputs.TO_BE_UPDATED }} == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.checker-diff-files.outputs.TAG_TO_UPDATE }}
        run: |
          cp -f neuvector/.github/upgrade-responder.json manifests/upgrade-responder/resources/ConfigMap/upgrade-responder.json
          BRANCH_NAME="${BRANCH_NAME_PREFIX}$TAG"
          echo "Creating and pushing branch: $BRANCH_NAME"
          git checkout -b "$BRANCH_NAME"
          git diff
          git add manifests/upgrade-responder/resources/ConfigMap/upgrade-responder.json
          git commit -m "Automated commit by GitHub Actions"            
          git push origin "$BRANCH_NAME"
          gh pr create --base main --head "$BRANCH_NAME" --title "Automated: Update Neuvector upgrade-responder.json to $TAG" --body "This PR updates the \`upgrade-responder.json\` file with the version \`$TAG\`, generated automatically by GitHub Actions. Check https://github.com/neuvector/neuvector/ for more info"
